# Generated by Django 4.2.1 on 2023-05-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('age', models.DateField(max_length=30)),
                ('sex', models.CharField(max_length=10)),
            ],
        ),
    ]
